### ISSUE TITLE
Deprecate deprecated GL functions in the bindings

### ISSUE THREAD

**Issue by AdMaioremDeiGloriam** [LWJGL/lwjgl#126]
`@Deprecated` tag should be added to all GL bindings that explicitly state they are deprecated, and documented with `@deprecated` and the associated reason for deprecation.

**Comment by Spasi** [comment]
This is a common request, but I'm afraid it cannot be implemented. It would be very annoying for users that use compatibility profile contexts. Which are many. Also, the deprecated functionality works just fine in modern drivers.

**Comment by LinkTheProgrammer** [comment]
Alright

**Comment by LinkTheProgrammer** [comment]
Although you could simply annotate the GL?? Classes with
`@SupressWarnings({"deprecated", "deprecation"})' unless you mean it would
be annoying to see crossed out method names in your code everywhere.

**Comment by Spasi** [comment]
Yes, I meant compiler warnings and crossed-out method names in the IDE.

**Comment by LinkTheProgrammer** [comment]
Crazy idea, but... LWJGL GL Compatibility build maybe? I have no right to
criticize what programmers choose to use, especially since I'm a GL noob,
but why even use the deprecated features in the first place besides
compatibility with a computer from 2008 and not rewriting your outdated
code? With things updating all the time, it seems counterintuitive. It's
like using HTML 1.0 and CSS 1.0 for being compatible with _every_ browser
ever made, when it is impractical to do so because you lose productivity.

**Comment by Spasi** [comment]
Except you don't lose productivity, the exact opposite. The deprecated functionality is very convenient to use and you can't replace it without a lot more code or non-trivial shaders.

Anyway, I don't think LWJGL needs to change, the core profile contexts do all the necessary validation and you will immediately know if you try to use deprecated functionality. Also, this repository is for LWJGL 2 which is not maintained anymore, any new development goes into [LWJGL 3](https://github.com/LWJGL/lwjgl3).

If you're looking for something really new and modern (and very hard to work on), wait a few months for [Vulkan](https://www.khronos.org/vulkan). LWJGL 3 will have bindings for it as soon as it's released.

**Comment by LinkTheProgrammer** [comment]
Didn't know that part. I just thought all one would need to do is simply to
use your GLSL shaders to modify data and just upload them to GL.

Vulkan seems promising and I will definitely use it when it comes out and
refactor my code as necessary.

**Comment by Caritas-Dei** [comment]
Closing for the reasons expressed by @Spasi . Old issue. This also does not appear to be something that would be done today either, even with OpenGL 4.6 and Vulkan already available; however, I would suggest creating a custom annotation `@LegacyGL` or otherwise aptly named to separate these functions (and constants, etc.) from the rest. IDEs that support syntax coloring, etc. for custom annotations will then be able to customize any warnings or special text rendering for this annotation, and it will not generate warnings nor errors, nor crossed-out text by default as is the case with `@Deprecated`.
